[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Humboldt-WI/adams/blob/master/exercises/Ex01-Python-Primer.ipynb) 


# Python primer #1: basics
Here is the outline of our first tutorial introducing Python and Jupyter notebooks.

1. Jupyter notebook
2. Python basics
3. Packages and installation
3. numpy
4. pandas
5. loading data
6. matpotlib

In [1]:
!python --version

Python 3.9.5


## Working with a Jupyter notebook
### Managing cells
Jupyter has two modes. When the cell marker is blue, you can select cells with the keyboard arrows and handle them by creating new cells, moving, copying or deleting them. When you press Enter while selecting a cell, you jump into editing mode and can change the content of a cell, e.g. by writing code.

The types of actions you can perform are listed under Help > Keyboard shortcuts 

- New cells are inserted with *a* (above) or *b* (below).
- Cells can be *c* copied, *x* cut and *v* pasted
- Cells are deleted by pressing *d* two times.
- To run a cell and select the next cell: Shift + Enter
- While typing, use Tab to finish the object name for you and Shift + Tab to see the documentation

It is worth remembering the shortcuts to work efficiently. Also check out notebook *magic* commands starting with % when things get more interesting.

### Cell types ###
A Jupyter notebook usually consists of text describing the context of the problem and describing the code as well as the actual code. Text is written in markup cells, which allow nice formatting similar to LaTeX, while code should be written in code cells. There, the code can be run interactively and the output will be visualized in the notebook.

You can change the cell content with 'm' for markup and 'y' for code. Remember that you need to be in selection (or command) mode. 

##functionality demo

## Python  ##

### Object types

1. _Numbers_: 1234, 3.1415, 999L, 3+4j, Decimal

2. _Strings_: 'ourstring', "text or comment"

3. _Lists_: [1, [2, 'three'], 4]

4. _Dictionaries_: {'employment': 'fulltime', 'gender': 'male'}

5. _Tuples_: (1,'spam', 4, 'U')

6. _Files_: myfile = open('goodcode', 'python')

also booleans, functions, classes, etc


## Lists and assignment rules
Unlike R, Python is primarily a programming language, so its standard object classes behave a little different. When indexing lists and similar objects, always remember that python starts counting indices at 0. When slicing x[start:end], the end value is *not* included in the output. You can index from the end using the minus like x[0:-2].

The biggest difference is that many objects can be modified in-place, i.e. without reassignment common in R like x <- x[1:2]. This increases speed and memory efficiency, but be careful when running code multiple times or in a different order. Also be aware that objects are not copied when reassigned, but instead linked to the original content, which may change. If you'd like to copy a list, use a complete index [:].



In [2]:
import dic as dic
!python --version

Python 3.8.8


In [3]:
# this is just a variable

x = 5
y = 'hello world'
type(y)


str

In [5]:

# Lists
x = [1, 2, 3, 4]
# print(x)
# type(x)
print(type(x))


list

In [6]:
# index our list
x[1:3]

[2, 3]

In [7]:
x[0]

1

In [8]:
x[-2]

3

In [9]:
# Delete an element of x in-place
# Also note that you can index from the end by using -
del x[-2]
print(x)

[1, 2, 4]


In [11]:
x = [1,2,3,4]
y = x
z = x[:] #this is a copy of the values, we assign the values of x to z
#y[0] = 9
z[0] = 8
print(y)
print(z)
print(x)

[1, 2, 3, 4]
[8, 2, 3, 4]
[1, 2, 3, 4]


In [12]:
del y[0]
y

[2, 3, 4]

In [13]:
# See that x has changed when we deleted y[0]
print(x); print(z)

[2, 3, 4]
[8, 2, 3, 4]


### Functions and Methods

Python is an object-oriented programming language, so in addition to functions, it has *methods*. Methods are associated with objects. That means they are called for a specific object instead of passing the object as an explicit argument and have access to information saved within the object.

Objects, in turn, are an instantiation of a class. Think of classes as templates, which define all the data and behavior (i.e., methods) of an entity. For example, a class _student_ could provide a programmer with means to store data such as _name_, _email_, and _student id_. In addition, the class could define some behavior that students exhibit, such as _enrollForCourse_, _registerForExam_, etc. The way to implement behavior is to write a corresponding method. Using the __class__ _student_, that is our template, we could then create __objects__ that represent individual students, such as a student with _name_ Eve and _student id_ 12345, and a different student with _name_ Paul and _student id_ 67890.

In [14]:
x = [1,2,3,4]
print(type(x))

<class 'list'>


In [15]:
z = x.copy()
# above is the same as
z = x[:]

In [18]:
type(z)

list

In [23]:
print(z)
z.append(1)
print(z)

[1, 2, 1]
[1, 2, 1, 1]


In [20]:
z.pop()
print(z)

[1, 2]


In [24]:
z.count(1)

3

In [25]:
# A method for class string
a = "hello world"
print(type(a))

a.upper()

<class 'str'>


'HELLO WORLD'

In [26]:
a.split()

['hello', 'world']

In [27]:
# Find all methods for an object
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [28]:
# As for lists, one of the most frequent methods would be append (when we want to add smth to the list)
out = [1,2,3,4,5]
out.append(100)
print(out)

[1, 2, 3, 4, 5, 100]


We will look more into methods when we are talking about packages

## Dictionaries
Dictionaries are similar to named lists in R, in that they save a value filed under a name (=key). When creating object classes, python makes use of different brackets. You will need it for data management.

In [8]:
# Dictionary
d = {"a":2, "b":"cheese", "c":[1,2,3], "d" : ['a', 'list', 'of', 'text' ]}
print(d)
print(d["c"])
print(d["b"])
print(d["d"])

{'a': 2, 'b': 'cheese', 'c': [1, 2, 3], 'd': ['a', 'list', 'of', 'text']}
[1, 2, 3]
cheese
['a', 'list', 'of', 'text']


In [30]:
print(d["c"])

[1, 2, 3]


In [12]:
d.keys()
# displays a list of keys that we defined in the dictionary

dict_keys(['a', 'b', 'c', 'd'])

In [32]:
d.values()
# displays a list of values of the dictionary

dict_values([2, 'cheese', [1, 2, 3], ['a', 'list', 'of', 'text']])

In [33]:
d.items()

dict_items([('a', 2), ('b', 'cheese'), ('c', [1, 2, 3]), ('d', ['a', 'list', 'of', 'text'])])

In [34]:
d[3] = 'NEW'
d

{'a': 2,
 'b': 'cheese',
 'c': [1, 2, 3],
 'd': ['a', 'list', 'of', 'text'],
 3: 'NEW'}

In [35]:
# dictionary for tuning random forest

rf_grid = {'mytr': [1,2,3,4], 'ntree': [10,100,200,1000]}
print(rf_grid)

{'mytr': [1, 2, 3, 4], 'ntree': [10, 100, 200, 1000]}


Mind the difference!

You can get the keys, items or both (as a list of tuples) at any time from the dictionary. Note that the 'functions' are methods that are part of each dictionary, so we use d.keys() instead of keys(d). We will talk more about the difference later.

In [36]:
print(d.keys())
print(d.values())
print(d.items())

dict_keys(['a', 'b', 'c', 'd', 3])
dict_values([2, 'cheese', [1, 2, 3], ['a', 'list', 'of', 'text'], 'NEW'])
dict_items([('a', 2), ('b', 'cheese'), ('c', [1, 2, 3]), ('d', ['a', 'list', 'of', 'text']), (3, 'NEW')])


## Conditions and Loops
Conditional structures are very important in order to create efficient programms. The logic resembles R, however, there is a bunch of notions you should be aware of. For example, __indentation__ (4 spaces per indentation level). Unlike R, Python is sensitive to it.

In [1]:
# simply condition
x = 'Python'

if x.lower() == 'python':
    print("So we program in Python")
    print('Great that is a nice language')
else:
    print("So we use some other programming language")

So we program in Python
Great that is a nice language


In [2]:
language="Python"
if language == 'Python':
 print('Mind the dents!')
elif x.lower() == 'java':
    print('Ok, so you probably do not do data science')
else:
 print("Ah, do whatever you want")
#just a space will also work in most cases, however, the Python community has developed a Style Guide for Python Code (PEP8) where the agreement is on 4 spaces

Mind the dents!


Sometimes we need a certain logical flow to be executed, that is where _else_ and _elseif_ would be useful:

In [3]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


In [4]:
# simple loop(s)
mylist = [1,2,3,4,5,6,7,8,9]
for v in mylist:
    print(v)
    print(v*2)

1
2
2
4
3
6
4
8
5
10
6
12
7
14
8
16
9
18


In [14]:
# process all the key-value pairs in our dictionary
for key, value in d.items():
    print ('The key {} corresponds to the value {}'.format(key,value))

The key a corresponds to the value 2
The key b corresponds to the value cheese
The key c corresponds to the value [1, 2, 3]
The key d corresponds to the value ['a', 'list', 'of', 'text']


In [9]:
type(d.items())

dict_items

In [15]:
d.items()

dict_items([('a', 2), ('b', 'cheese'), ('c', [1, 2, 3]), ('d', ['a', 'list', 'of', 'text'])])

In [21]:
mlist = [1,2,3,4,5,6]
[x*2 for x in mlist]
# a more condensed way of writing a for loop

[2, 4, 6, 8, 10, 12]

Let's try to apply a certain action to every component of a list with a use of looping command __for__:

In [22]:
ourstring=[5,8,9,7]
for thingy in ourstring:
    print(thingy)
#You won't be able to do much with the list - that is why we will need Numpy or a function

5
8
9
7


In [23]:
#Some other actions are also possible
for dingy in ourstring:
    print(dingy+dingy)

10
16
18
14


__While__ and __for__ are other examples of looping command:

In [24]:
j = -1
while j < 8:
    print('i is: {}'.format(j))
    j = j+1

i is: -1
i is: 0
i is: 1
i is: 2
i is: 3
i is: 4
i is: 5
i is: 6
i is: 7


In [25]:
for z in range(7):
    print(z)

0
1
2
3
4
5
6


It is often useful to loop over several values at the same time, for example over each key and value pair in a dictionary. 

In [27]:
for key, value in d.items():
    print(f"This is one of the keys: {key}")
    print(f"And this is its value: {value}")

This is one of the keys: a
And this is its value: 2
This is one of the keys: b
And this is its value: cheese
This is one of the keys: c
And this is its value: [1, 2, 3]
This is one of the keys: d
And this is its value: ['a', 'list', 'of', 'text']


In [28]:
mylist = [1,2,3,4,5,6,7,8,9]
[x*2 for x in mylist]


[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [29]:
#it looks much nicer if we form the operation above like this
for x in mylist:
    x = x*2
    print(x)
x

2
4
6
8
10
12
14
16
18


Very often, we can use comprehensions that return an object with the results directly.

In [30]:
v=[1,5,9,19]
[x*2 for x in v] #

[2, 10, 18, 38]

In [31]:
d.items()

dict_items([('a', 2), ('b', 'cheese'), ('c', [1, 2, 3]), ('d', ['a', 'list', 'of', 'text'])])

In [32]:
{key:value=="cheese" for key,value in d.items()}

{'a': False, 'b': True, 'c': False, 'd': False}

### Functions
Functions work as in R. You create new function by *defining* them. You see that much of structural programming is indicated by the structure of the code, i.e. a tab or four spaces.


In [33]:
def ourFunction (arg1, arg2, arg3 ...):
    program statement1
    program statement3
    program statement3
    ....
    return;

SyntaxError: invalid syntax (<ipython-input-33-b66bd38b77eb>, line 1)

In [34]:
def happyBirthdayAlisa(): #program does nothing as written
    print("Happy Birthday to you!")
    print("Happy Birthday to you!")
    print("Happy Birthday, dear Alisa.")
    print("Happy Birthday to you!")

In [35]:
happyBirthdayAlisa # what happened

<function __main__.happyBirthdayAlisa()>

In [36]:
happyBirthdayAlisa()

Happy Birthday to you!
Happy Birthday to you!
Happy Birthday, dear Alisa.
Happy Birthday to you!


In [37]:
def happyBirthday(person):
    print("Happy Birthday to you!")
    print("Happy Birthday to you!")
    print("Happy Birthday, dear " + person + ".")
    print("Happy Birthday to you!")
happyBirthday("Christian")

Happy Birthday to you!
Happy Birthday to you!
Happy Birthday, dear Christian.
Happy Birthday to you!


In [40]:
def multpl(x, y):
    return x ** y

multpl(5,3)

125

In [44]:
# In simple cases like the one above we can use an anonymous function like the ones we know from R:

r = lambda x, y:x * y
r(120, 5) 

600

In [46]:
# Let's look more into the structure
def example_function(x, y = 2):
    x += y # This is short for add and reassign x = x + y
    return x
x

18

In [47]:
example_function(1)

3

In [48]:
#You can build your whole code as execution of certain functions
def main():
    happyBirthday('Bobby')
    happyBirthday('Anna')
main()

Happy Birthday to you!
Happy Birthday to you!
Happy Birthday, dear Bobby.
Happy Birthday to you!
Happy Birthday to you!
Happy Birthday to you!
Happy Birthday, dear Anna.
Happy Birthday to you!


### Methods as functions attached to a class

In [2]:
class person():
    """Class person for human interaction"""
    def __init__(self, name, age=None):
        """
        Cool, we can write help text like this starting and ending 
        with three quotations.
        
        name : str
          The name of the person
        """
        self.name = name
        self.age = age
     
        
    def happy_birthday(self):
        """Wish a happy birtday"""
        print(f"Happy Birthday, dear {self.name}.")
        #should be written as: print("Happy Birthday,dear {}-." .format(self.name))
        if self.age is not None:
            self.age += 1
            print(f"{self.age} years, eh?")
        return None
    
    def greeting(self):
        """Greet the person"""
        print(f"Hi {self.name}! How are you doing?")
        return None




In [9]:
example = person("Johannes", 20)
example.happy_birthday()

Happy Birthday, dear Johannes.
21 years, eh?


In [10]:
second_person = person("Mirza", 33)
second_person.greeting()

Hi Mirza! How are you doing?


In [11]:
second_person.age #check age of the second person

33

In [19]:
from platform import python_version
print(python_version())


3.8.5


In [6]:
!python --version

Python 3.9.5


In [12]:
example.happy_birthday()

Happy Birthday, dear Johannes.
22 years, eh?


In [13]:
second_person.happy_birthday()

Happy Birthday, dear Mirza.
34 years, eh?


In [23]:
example.age

23

In [15]:
# A Sample class with init method
class Person:

    # init method or constructor
    def __init__(self, name):
       self.name = name

    # Sample Method
    def say_hi(self):
        print('Hello, my name is', self.name)

p = Person('Nikhil')
p.say_hi()

Hello, my name is Nikhil


## Loading libraries aka packages
Most of the functionality that we need is provided by additional libraries to the core python. You can do it in several ways:
 1. Install manually via Anaconda Netvigator (Environments)
 2. Install via Anaconda terminal (advised at set-up stage) **- recommended**
 3. Install in Jupyter notebook (!{sys.executable} -m pip install numpy __OR__ !conda install --yes --prefix {sys.prefix} numpy)
 4. Install in Jupyter notebook via !pip install  - not recommended

In [ ]:
import sys
!conda install  --prefix {sys.prefix} numpy

At the beginning of the code, we need to load these packages. Python is stricter than R when it comes to namespaces. When loading a function from a package, the package is usually included in the function call. For convenience, package names are therefore often abbreviated using import [...] as [...]. It is also possible to import only specific function from a library using from 'package' import 'function'.

The top 5 packages to remember for now are:
 - numpy (numeric manipulation)
 - pandas (data management)
 - matplotlib (plots)
 - seaborn (advanced plots, stat visualizations)
 - scikit-learn (standard package for machine learning in python)
 
When loading packages, you can give them a nickname in order to save some typing time. There usually is a convention for each package's nickname, but you can choose a different one.

In [9]:
# Math functionality
import numpy as np
# Data frame capabilities similar to data.table in R
import pandas as pd
# Plotting functionality
import matplotlib.pyplot as plt
%matplotlib inline
# Statistical data visualization
import seaborn as sns
# scikit-learn (sklearn) is *the* standard package for machine learning in python

## Numpy

Numpy will do most of the linear algebra operations on the way. We will look into:
- arrays
- indexing
- operations

In [3]:

import numpy as np
# numpy array is one of the most basic object types, we can get it by converting a basic list

In [4]:
ourlist = [1,2,3,4,5]
ourlist
np.array(ourlist)

array([1, 2, 3, 4, 5])

In [5]:
import pandas as pd
pd.array(ourlist)

<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64

Note how we specify the package by its nickname before calling a function from the package

In [6]:
x = np.array(ourlist)
x


array([1, 2, 3, 4, 5])

In [7]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [8]:
#Some basic operations
print(np.sqrt(ourlist),np.exp(ourlist))
# but it can also be written as np.sqrt(x), np.exp(ourlist)

[1.         1.41421356 1.73205081 2.         2.23606798] [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [9]:
listoflists=[[1,2,3],[4,5,6],[7,8,9]]
listoflists
#len (listoflists[0])
# ln returns a number of items in a container

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
[[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]]

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [11]:
np.array(listoflists) # for our neural networks it will be the most basic type

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#Learning to operate them would be important
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,12,3) # specifying an increment

array([0, 3, 6, 9])

In [18]:
np.ones((3,4)) # generating a matrix of 1, could be 0
# np.zeros((3,4)) # generating a matrix of 0
# np.eye(3,3) # creating a identity matrix

TypeError: Cannot interpret '4' as a data type

In [15]:
np.linspace(0,5,10) # evenly spaced numbers in specified interval

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Setting a value with index range (Broadcasting)
ar = np.arange(0,20)
ar[0:5]=0 #change the first 5 elements of the array to 0
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
#Important note!
slice_of_ar = ar[0:4]
slice_of_ar

array([0, 1, 2, 3])

In [22]:
slice_of_ar[:]=999
slice_of_ar

array([999, 999, 999, 999])

Note that change occurs in initial array!

In [23]:
ar

array([999, 999, 999, 999,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

We can copy objects actively to avoid this

In [24]:
slice_of_ar=ar[0:4].copy()
slice_of_ar

array([999, 999, 999, 999])

In [28]:
slice_of_ar[:]=0
slice_of_ar
ar

array([999, 999, 999, 999,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

Indexing is similar to R and works by integer index or logical index

In [29]:
x = 10
ar[ar>x]

array([999, 999, 999, 999,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [31]:
#Randomization will matter a lot for us
np.random.randn(2,4)

array([[ 0.46648379,  0.07622898,  0.10233379,  0.4909096 ],
       [-1.48465646,  1.43644144,  0.44666211,  0.66876262]])

In [32]:
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1,100,5) 

array([13, 13, 15, 60, 96])

In [33]:
arr = np.arange(25)
arr #arr.TAB will show you which methods you can use

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.max()

24

In [35]:
arr.reshape(5,5) # another important method 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(25,)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.shape # mind that the shape wasn't reassigned in-place

(25,)

In [38]:
arr.reshape(25,1).shape

(25, 1)

In [35]:
arr.dtype # for neural networks a specific type of float would be necessary, we will get back to  it later

dtype('int32')

In [39]:
w =np.array([12,11,10])
v = np.array([1,2,3])

In [40]:
# Inner product of vectors;
print(v.dot(w))
print(np.dot(v, w))

64
64


In [41]:
# Matrix/vector multiplication
import numpy as np
A = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print (A.dot(b))

[16  6  8]


In [42]:
#Just a quick reminder about the element selection
print(A[0,0])
A

5


array([[5, 1, 3],
       [1, 1, 1],
       [1, 2, 1]])

In [43]:
#Let's say we have A x = b, we need to find x

A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]]))

#To solve the system we do
x=np.linalg.solve(A,b)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [44]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
A

array([[ 2,  1, -2],
       [ 3,  0,  1],
       [ 1,  1, -1]])

In [45]:
b = np.transpose(np.array([[-3,5,-2]]))
b

array([[-3],
       [ 5],
       [-2]])

In [47]:
c = np.array([[-3,5,-2]])
c

array([[-3,  5, -2]])

In [46]:
d = np.transpose(np.array([[-3,5,-2]]))
d

array([[-3],
       [ 5],
       [-2]])

That was it for our first session. See you soon for another round of programming.




SyntaxError: invalid syntax (<ipython-input-3-7e5b5744133c>, line 1)